# Generated by Django 4.1.7 on 2023-03-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='form_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('offprice', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('proimage', models.ImageField(upload_to='product/')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app8.catagory_tb')),
            ],
        ),
        migrations.CreateModel(
            name='reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('hashpassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app8.form_tb')),
            ],
        ),
    ]
