# Generated by Django 4.1.7 on 2023-03-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_admin_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
