# Generated by Django 4.1.3 on 2023-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0003_contact_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_tb',
        ),
    ]
